$(document).ready(function(){
    $(document).on('click','.dropbtn2',function(){
        $('.dropbtn2').not(this).next().removeClass('show');
        $(this).next().toggleClass('show');
    });
    $(document).on('click',function(e){
        if(!$(e.target).closest('.dropbtn2').length)
        $('.dropbtn2').next().removeClass('show');
    });    
});